### ISSUE TITLE
singbox启动失败

### ISSUE THREAD

**Issue by biancong1208** [kwaa/comet#1]
感谢作者，终于找到naiveproxy的透明代理了，再次感谢！

环境：斐讯N1 Armbian OS 24.5.0 Bullseye with Linux 5.15.149-ophub

sing-box exited with code 1
naive       | [0303/145929.382671:INFO:naive_connection.cc(275)] Connection 37 to github.com:443
sing-box    | WARN[0000] router: geoip database not exists: /data/geoip.db
naive       | [0303/145929.595865:INFO:naive_proxy.cc(192)] Connection 37 closed: OK
sing-box    | ERROR[0000] router: download geoip database: Get "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db": EOF
naive       | [0303/145929.600632:INFO:naive_connection.cc(275)] Connection 38 to github.com:443
naive       | [0303/145929.815708:INFO:naive_proxy.cc(192)] Connection 38 closed: OK
sing-box    | ERROR[0000] router: download geoip database: Get "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db": EOF
naive       | [0303/145929.820140:INFO:naive_connection.cc(275)] Connection 39 to github.com:443
naive       | [0303/145930.035676:INFO:naive_proxy.cc(192)] Connection 39 closed: OK
sing-box    | ERROR[0000] router: download geoip database: Get "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db": EOF
sing-box    | FATAL[0000] start service: Get "https://github.com/1715173329/sing-geoip/releases/latest/download/geoip.db": EOF

**Comment by kwaa** [comment]
看起来是因为下载不到 geoip，你可以把这两个文件下载好放在 ./sing-box 文件夹里

https://github.com/kwaa/comet/blob/dcc27b227ed80332db9c5842ed9b83bd188a1abd/sing-box/config.json#L58

https://github.com/kwaa/comet/blob/dcc27b227ed80332db9c5842ed9b83bd188a1abd/sing-box/config.json#L63

**Comment by biancong1208** [comment]
感谢回复，geoip放好后，错误如下：
root@armbian:/opt/comet# docker-compose up
Starting naive ... done
Starting sing-box ... done
Attaching to naive, sing-box
naive       | [0303/154145.322636:INFO:naive_proxy_bin.cc(484)] Proxying via https://rack.biancong.top
naive       | [0303/154145.469060:INFO:naive_proxy_bin.cc(686)] Listening on socks://0.0.0.0:1080
naive       | [0303/154225.323515:INFO:naive_proxy.cc(192)] Connection 1 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0039] [3116089054 5ms] inbound/tun[tun-in]: socks5: request rejected, code=7
sing-box    | ERROR[0171] [1771018869 5ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/154436.886846:INFO:naive_proxy.cc(192)] Connection 2 closed: ERR_SOCKS_CONNECTION_FAILED

**Comment by kwaa** [comment]
检查一下有没有修改 sing-box 配置

https://github.com/kwaa/comet#%E7%94%A8%E6%B3%95

**Comment by biancong1208** [comment]
已把sing-box 配置中的comet.local修改为域名，主要表现为能上国内网址，但是不能翻墙。

**Comment by biancong1208** [comment]
错误如下：
naive       | [0303/162111.137276:INFO:naive_proxy_bin.cc(484)] Proxying via https://rack.biancong.top
naive       | [0303/162111.288855:INFO:naive_proxy_bin.cc(686)] Listening on socks://0.0.0.0:1080
sing-box    | ERROR[0007] dns: transport not found: dns_direct
sing-box    | ERROR[0007] dns: transport not found: dns_direct
naive       | [0303/162118.723176:INFO:naive_proxy.cc(192)] Connection 1 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0007] dns: exchange failed for ecpm.tanx.com. IN AAAA: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0007] dns: exchange failed for ecpm.tanx.com. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162130.399475:INFO:naive_proxy.cc(192)] Connection 2 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0018] dns: exchange failed for mima.biancong.top. IN AAAA: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162132.053756:INFO:naive_connection.cc(275)] Connection 3 to 34.110.207.168:443
naive       | [0303/162132.068501:INFO:naive_proxy.cc(192)] Connection 4 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0020] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162135.182275:INFO:naive_proxy.cc(192)] Connection 5 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0023] dns: exchange failed for www.olehdtv.com. IN AAAA: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0023] dns: exchange failed for www.olehdtv.com. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162137.070433:INFO:naive_proxy.cc(192)] Connection 6 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0025] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162137.139996:INFO:naive_connection.cc(275)] Connection 7 to 172.217.163.36:443
naive       | [0303/162137.834836:INFO:naive_connection.cc(275)] Connection 8 to 172.217.163.36:443
naive       | [0303/162138.064983:INFO:naive_proxy.cc(192)] Connection 9 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0026] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162140.825756:INFO:naive_connection.cc(275)] Connection 10 to 23.206.250.66:80
sing-box    | ERROR[0030] dns: transport not found: dns_direct
naive       | [0303/162142.077078:INFO:naive_proxy.cc(192)] Connection 11 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0030] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162143.066392:INFO:naive_proxy.cc(192)] Connection 12 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0031] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162143.402555:INFO:naive_connection.cc(275)] Connection 13 to 20.187.186.89:443
sing-box    | ERROR[0035] dns: transport not found: dns_direct
naive       | [0303/162147.080149:INFO:naive_proxy.cc(192)] Connection 14 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0035] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0036] dns: transport not found: dns_direct
naive       | [0303/162148.077365:INFO:naive_proxy.cc(192)] Connection 15 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0036] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162150.066553:INFO:naive_proxy.cc(192)] Connection 16 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0038] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162152.072322:INFO:naive_proxy.cc(192)] Connection 3 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162152.072493:INFO:naive_proxy.cc(192)] Connection 8 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162152.072576:INFO:naive_proxy.cc(192)] Connection 7 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162152.072655:INFO:naive_proxy.cc(192)] Connection 10 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162152.072869:INFO:naive_proxy.cc(192)] Connection 13 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162152.103509:INFO:naive_connection.cc(275)] Connection 17 to 20.187.186.89:443
naive       | [0303/162152.113826:INFO:naive_proxy.cc(192)] Connection 18 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0040] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0041] dns: transport not found: dns_direct
naive       | [0303/162153.074102:INFO:naive_proxy.cc(192)] Connection 19 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0041] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162155.069921:INFO:naive_proxy.cc(192)] Connection 20 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0043] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162157.118629:INFO:naive_proxy.cc(192)] Connection 21 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0045] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162157.595159:INFO:naive_connection.cc(275)] Connection 22 to 20.198.162.76:443
naive       | [0303/162158.116709:INFO:naive_proxy.cc(192)] Connection 23 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0046] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162158.167875:INFO:naive_connection.cc(275)] Connection 24 to 172.217.163.36:443
naive       | [0303/162158.286873:INFO:naive_connection.cc(275)] Connection 25 to 23.206.250.114:80
sing-box    | ERROR[0048] dns: transport not found: dns_direct
naive       | [0303/162200.077003:INFO:naive_proxy.cc(192)] Connection 26 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0048] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0050] dns: transport not found: dns_direct
sing-box    | ERROR[0050] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162202.122233:INFO:naive_proxy.cc(192)] Connection 27 closed: ERR_SOCKS_CONNECTION_FAILED
naive       | [0303/162202.358787:INFO:naive_connection.cc(275)] Connection 28 to 184.26.241.154:443
naive       | [0303/162203.120137:INFO:naive_proxy.cc(192)] Connection 29 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0051] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0053] dns: transport not found: dns_direct
naive       | [0303/162205.075339:INFO:naive_proxy.cc(192)] Connection 30 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0053] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
sing-box    | ERROR[0055] dns: transport not found: dns_direct
naive       | [0303/162207.121963:INFO:naive_proxy.cc(192)] Connection 31 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0055] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162207.589282:INFO:naive_connection.cc(275)] Connection 32 to 174.37.154.236:443
sing-box    | ERROR[0056] dns: transport not found: dns_direct
naive       | [0303/162208.124043:INFO:naive_proxy.cc(192)] Connection 33 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0056] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162210.111592:INFO:naive_proxy.cc(192)] Connection 34 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0058] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162210.991610:INFO:naive_connection.cc(275)] Connection 35 to 20.198.162.76:443
naive       | [0303/162212.118210:INFO:naive_proxy.cc(192)] Connection 17 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.118336:INFO:naive_proxy.cc(192)] Connection 35 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.118370:INFO:naive_proxy.cc(192)] Connection 24 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.118399:INFO:naive_proxy.cc(192)] Connection 25 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.118427:INFO:naive_proxy.cc(192)] Connection 28 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.118456:INFO:naive_proxy.cc(192)] Connection 32 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.118496:INFO:naive_proxy.cc(192)] Connection 22 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/162212.137328:INFO:naive_connection.cc(275)] Connection 36 to 20.198.162.76:443
naive       | [0303/162212.138899:INFO:naive_connection.cc(275)] Connection 37 to 20.198.162.76:443
naive       | [0303/162212.147785:INFO:naive_proxy.cc(192)] Connection 38 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0060] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162212.322605:INFO:naive_proxy.cc(192)] Connection 39 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0060] dns: exchange failed for ext1-tyo3.steamserver.net. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162212.566551:INFO:naive_connection.cc(275)] Connection 40 to 103.10.124.122:27023
naive       | [0303/162212.570280:INFO:naive_connection.cc(275)] Connection 41 to 103.10.124.122:27020
naive       | [0303/162212.630175:INFO:naive_connection.cc(275)] Connection 43 to 45.121.184.20:443
naive       | [0303/162212.630706:INFO:naive_connection.cc(275)] Connection 42 to 103.10.124.122:443
sing-box    | ERROR[0061] dns: transport not found: dns_direct
naive       | [0303/162213.127656:INFO:naive_proxy.cc(192)] Connection 44 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0061] dns: exchange failed for rack.biancong.top.lan. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162213.623184:INFO:naive_connection.cc(275)] Connection 45 to 103.28.54.172:27032
sing-box    | ERROR[0063] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162215.122315:INFO:naive_proxy.cc(192)] Connection 46 closed: ERR_SOCKS_CONNECTION_FAILED
naive       | [0303/162217.151365:INFO:naive_proxy.cc(192)] Connection 47 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0065] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162218.151382:INFO:naive_proxy.cc(192)] Connection 48 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0066] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7

**Comment by kwaa** [comment]
啊，我上传的时候写错了

https://github.com/kwaa/comet/blob/dcc27b227ed80332db9c5842ed9b83bd188a1abd/sing-box/config.json#L50

这块改成 `dns-direct`

**Comment by biancong1208** [comment]
大佬辛苦了，这么晚了还不睡，修改以后好像还是报一样的错误：
naive       | [0303/162939.890829:INFO:naive_proxy_bin.cc(484)] Proxying via https://rack.biancong.top
naive       | [0303/162940.037819:INFO:naive_proxy_bin.cc(686)] Listening on socks://0.0.0.0:1080
naive       | [0303/162950.158694:INFO:naive_connection.cc(275)] Connection 1 to 172.217.163.36:443
naive       | [0303/162950.169659:INFO:naive_proxy.cc(192)] Connection 2 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0009] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162954.944836:INFO:naive_proxy.cc(192)] Connection 3 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0014] [3062894004 6ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/162955.174563:INFO:naive_proxy.cc(192)] Connection 4 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0014] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162956.167401:INFO:naive_proxy.cc(192)] Connection 5 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0015] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/162957.992189:INFO:naive_proxy.cc(192)] Connection 6 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0017] [352359207 5ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/163000.465880:INFO:naive_proxy.cc(192)] Connection 1 closed: ERR_PROXY_CONNECTION_FAILED
naive       | [0303/163001.037584:INFO:naive_proxy.cc(192)] Connection 7 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0020] [4184179915 4ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/163001.175762:INFO:naive_proxy.cc(192)] Connection 8 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0020] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/163003.974641:INFO:naive_proxy.cc(192)] Connection 9 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0023] [3803343540 6ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/163004.095289:INFO:naive_proxy.cc(192)] Connection 10 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0023] [1161808308 3ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/163005.026192:INFO:naive_proxy.cc(192)] Connection 11 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0024] [2724144787 4ms] inbound/tun[tun-in]: socks5: request rejected, code=7
naive       | [0303/163005.867514:INFO:naive_connection.cc(275)] Connection 12 to 35.186.227.140:443
naive       | [0303/163005.876913:INFO:naive_proxy.cc(192)] Connection 13 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0025] dns: exchange failed for rack.biancong.top. IN A: Post "https://1.1.1.1/dns-query": socks5: request rejected, code=7
naive       | [0303/163007.141488:INFO:naive_proxy.cc(192)] Connection 14 closed: ERR_SOCKS_CONNECTION_FAILED
sing-box    | ERROR[0026] [3363633650 6ms] inbound/tun[tun-in]: socks5: request rejected, code=7

**Comment by kwaa** [comment]
有点奇怪，我明天对比一下本地配置
这个 naive 拿出来单独用能连上吗

**Comment by biancong1208** [comment]
嗯嗯，谢谢大佬！我用openwrt的passwall是可以连接的，谢谢大佬的热心帮助。

**Comment by kwaa** [comment]
更新了 sing-box 配置，可以 git pull 再试试

**Comment by biancong1208** [comment]
成功了！！！太棒了！！！终于可以继续用naive了，谢谢大佬！！！
