### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by chent1001** [kwaa/comet#2]
docker: Error response from daemon: No command specified.

**Comment by kwaa** [comment]
This is related to your local Docker environment, not a comet issue. You can try reinstalling Docker and Docker Compose or checking to see if it's the latest version.

**Comment by chent1001** [comment]
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:49 2024
 OS/Arch:           linux/amd64
 Context:           default
 
 `
docker run --dt \
--name naive \
--network host \
-v /etc/naive/config.json:/etc/naive/config.json \
--restart unless-stopped \
kwaabot/naive
`

docker: Error response from daemon: no command specified.
